<a href="https://colab.research.google.com/github/abdulmajidalali17-oss/Machine-Learning/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
# Creating a series of car types
cars = pd.Series(["BMW", "Toyota", "Honda"])
cars

0       BMW
1    Toyota
2     Honda
dtype: object

In [ ]:
# Creating a series of colours
colours = pd.Series(["Blue", "Red", "White"])
colours

0     Blue
1      Red
2    White
dtype: object

In [ ]:
# Creating a DataFrame of cars and colours
car_data = pd.DataFrame({"Car type": cars,
                         "Colour": colours})
car_data

  Car type Colour
0      BMW   Blue
1   Toyota    Red
2    Honda  White

In [ ]:
import pandas as pd

data = {
    "Name": ["Ali", "Ahmad", "Omar", "Sara", "Maya"],
    "Age": [22, 25, 21, 24, 23],
    "Salary": [800, 1200, 700, 1500, 1100],
    "Department": ["IT", "AI", "IT", "HR", "AI"]
}

df = pd.DataFrame(data)

df.to_csv("employees.csv", index=False)

print("CSV file created!")

CSV file created!

In [ ]:
import pandas as pd

df = pd.read_csv("employees.csv")

print(df)

    Name  Age  Salary Department
0    Ali   22     800         IT
1  Ahmad   25    1200         AI
2   Omar   21     700         IT
3   Sara   24    1500         HR
4   Maya   23    1100         AI

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

df = pd.read_csv(url)

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.shape

(891, 12)

In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
import pandas as pd

# Print the version
print(f"pandas version: {pd.__version__}")

pandas version: 2.2.3

In [ ]:
# Creating a series of car types
cars = pd.Series(["BMW", "Toyota", "Honda"])
cars

0       BMW
1    Toyota
2     Honda
dtype: object

In [ ]:
# Creating a series of colours
colours = pd.Series(["Blue", "Red", "White"])
colours

0     Blue
1      Red
2    White
dtype: object

In [ ]:
# Creating a series of colours
colours = pd.Series(["Blue", "Red", "White"])
colours

0     Blue
1      Red
2    White
dtype: object

In [ ]:
# Creating a DataFrame of cars and colours
car_data = pd.DataFrame({"Car type": cars,
                         "Colour": colours})
car_data

  Car type Colour
0      BMW   Blue
1   Toyota    Red
2    Honda  White

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving car-sales.csv to car-sales.csv

In [ ]:
import pandas as pd

# Import the car sales data
df = pd.read_csv("car-sales.csv")

# Display the data
df

     Make Colour  Odometer (KM)  Doors        Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [ ]:
df.to_csv("car-sales-exported.csv", index=False)

In [ ]:
from google.colab import files

files.download("car-sales-exported.csv")

In [ ]:
from google.colab import files

files.download("car-sales-exported.csv")

In [ ]:
df.describe()

       Odometer (KM)      Doors
count      10.000000  10.000000
mean    78601.400000   4.000000
std     61983.471735   0.471405
min     11179.000000   3.000000
25%     35836.250000   4.000000
50%     57369.000000   4.000000
75%     96384.500000   4.000000
max    213095.000000   5.000000

In [ ]:
len(df)

10

In [ ]:
df.head()

     Make Colour  Odometer (KM)  Doors        Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Make           10 non-null     object
 1   Colour         10 non-null     object
 2   Odometer (KM)  10 non-null     int64
 3   Doors          10 non-null     int64
 4   Price          10 non-null     object
dtypes: int64(2), object(3)
memory usage: 532.0+ bytes

In [ ]:
df.loc[0]

Make                 Toyota
Colour                White
Odometer (KM)        150043
Doors                     4
Price            $4,000.00
Name: 0, dtype: object

In [ ]:
df.loc[0, "Make"]

'Toyota'

In [ ]:
df["Price"].sum()

'$4,000.00 $5,000.00 $7,000.00 $22,000.00 $3,500.00 $4,500.00 $7,500.00 $7,000.00 $6,250.00 $9,700.00 '

In [ ]:
df["Odometer (KM)"]

0    150043
1     87899
2     32549
3     11179
4    213095
5     99213
6     45698
7     54738
8     60000
9     31600
Name: Odometer (KM), dtype: int64

In [ ]:
df.groupby("Make")